version: "3.7"
services:
  app:
    build:
      args:
        user: panic
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    command: npm run build
    image: bootscreen
    ports:
      - ${APP_PORT}:80
    restart: unless-stopped
    environment:
      APP_PORT: ${APP_PORT}
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - bootscreen

networks:
  bootscreen:
    driver: bridge

